apiVersion: v1
kind: Secret
metadata:
  name: library-secret
  namespace: library-system
type: Opaque
data:
  DATABASE_USER: bGlicmFyeQ==
  DATABASE_PASSWORD: bGlicmFyeV9wYXNz
  JWT_SECRET: c3VwZXJfc2VjcmV0X2tleV9jaGFuZ2VfbWU=
  ADMIN_EMAIL: YWRtaW5AbGlicmFyeS5jb20=
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: QWRtaW4xMjMh
