apiVersion: v1
kind: Service
metadata:
  name: library-service
  namespace: library-system
  labels:
    app: library-service
spec:
  selector:
    app: library-service
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: library-service-lb
  namespace: library-system
  labels:
    app: library-service
spec:
  selector:
    app: library-service
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
